version: '3.8'

services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
    depends_on:
      - redis
      - identity-service
      - hotel-service
      - booking-service
      - payment-service
    networks:
      - hotel-network
    restart: unless-stopped

  identity-service:
    build: ./indentity-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - hotel-network
    restart: unless-stopped

  hotel-service:
    build: ./hotel_service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - hotel-network
    restart: unless-stopped

  booking-service:
    build: ./booking-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - hotel-network
    restart: unless-stopped

  payment-service:
    build: ./Payment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - hotel-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - hotel-network
    restart: unless-stopped

networks:
  hotel-network:
    driver: bridge

volumes:
  redis-data: 